name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Target
      run: rustup target install thumbv7em-none-eabihf
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target=thumbv7em-none-eabihf --verbose
    - name: Run tests
      run: cargo test --verbose
